Style changes, added quotes to everything, added a QOS field in output (but not functionality)

diff --git a/sinteractive b/sinteractive
--- a/sinteractive
+++ b/sinteractive
@@ -11,58 +11,57 @@
 # The result is very similar to an interactive shell in PBS
 # (qsub -I)
 
-MYDIR="$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"
+MYDIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}" )" )"
 
 # or
 #MYDIR=/usr/local/bin
 
 # Batch Script that starts SCREEN
-BS=$MYDIR/_interactive
+BS="$MYDIR/_interactive"
 # Interactive screen script
-IS=$MYDIR/_interactive_screen
+IS="$MYDIR/_interactive_screen"
 
 #Lets set some defaults with the next verison of this script offering ways to change
 REQCPU="2"
 REQMEM="8192"
 REQTIME="24:00:00"
+QOS="free"
 
 #Prompts to change will go here  (aka TODO)
 echo " "
-echo "### If the job fails to start, make sure you have a --qos= option defined###"
+echo "### If the job fails to start, ensure you have a --qos= option defined ###"
 echo " "
 echo " "
 echo "Spawning job with the following resources:"
 echo "     Processors: ${REQCPU}"
 echo "         Memory: ${REQMEM}"
 echo "  Runtime limit: ${REQTIME}"
+echo "            QOS: ${QOS}"
 echo " "
 
 # Submit the job and get the job id
-JOB=`sbatch --cpus-per-task=${REQCPU} --mem=${REQMEM} --time=${REQTIME} --output=/dev/null --error=/dev/null $@ $BS 2>&1 \
-    | egrep -o -e "\b[0-9]+$"`
-
-#ORIGNAL THAT WORKS
-#JOB=`sbatch --output=/dev/null --error=/dev/null $@ $BS 2>&1 \
-#    | egrep -o -e "\b[0-9]+$"`
+JOB="$( sbatch --cpus-per-task="${REQCPU}" --mem="${REQMEM}" \
+    --time="${REQTIME}" --output=/dev/null \
+    --error=/dev/null "$@" "$BS" |& egrep -o -e "\b[0-9]+$" )"
 
 # Make sure the job is always canceled
 # Relying on $PATH for scancel
-trap "{ scancel -q $JOB; exit; }" SIGINT SIGTERM EXIT
+trap "{ scancel -q "$JOB"; exit; }" SIGINT SIGTERM EXIT
 
 echo "Waiting for JOBID $JOB to start"
-while true;do
+while : ; do
     sleep 1s
 
     # Check job status
-    STATUS=`squeue -j $JOB -t PD,R -h -o %t`
+    STATUS="$( squeue -j "$JOB" -t PD,R -h -o %t )"
 
-    if [ "$STATUS" = "R" ];then
-	# Job is running, break the while loop
-	break
-    elif [ "$STATUS" != "PD" ];then
-	echo "Job is not Running or Pending. Aborting"
-	scancel $JOB
-	exit 1
+    if [[ "$STATUS" = "R" ]];then
+        # Job is running, break the while loop
+        break
+    elif [[ "$STATUS" != "PD" ]];then
+        echo "Job is not Running or Pending. Aborting"
+        scancel "$JOB"
+        exit 1
     fi
 
     echo -n "."
@@ -70,10 +69,9 @@ while true;do
 done
 
 # Determine the first node in the job:
-NODE=`srun --jobid=$JOB -N1 hostname`
+NODE="$( srun --jobid="$JOB" -N1 hostname )"
 
 # SSH to the node and attach the screen
 sleep 1s
-ssh -X -c arcfour -C -t $NODE $IS slurm$JOB
+ssh -X -c arcfour -C -t "$NODE" "$IS" "slurm$JOB"
 # The trap will now cancel the job before exiting.
-
