Tweaked author header; added in some handy dandy colorized output functions

diff --git a/sinteractive b/sinteractive
--- a/sinteractive
+++ b/sinteractive
@@ -1,10 +1,8 @@
 #!/bin/bash
 # -*- coding: utf-8 -*-
-# Author: Pär Andersson (National Supercomputer Centre, Sweden)
-# Version: 0.3 2007-07-30
-#
-# 2011-06-23: Joerg Bornschein <bornschein@fias.uni-frankfurt.de>
-#   Make this script find its own path
+# Authors: Pär Andersson (National Supercomputer Centre, Sweden)
+#          Paul Mezzanini (Rochester Institute of Technology, USA)
+#          Josh McSavaney (Rochester Institute of Technology, USA)
 #
 # This will submit a batch script that starts screen on a node.
 # Then ssh is used to connect to the node and attach the screen.
@@ -13,6 +11,49 @@
 
 set -e
 
+function TPUT()
+{
+    #check for TTY and tput and redefine our existence based upon the results
+    if [[ -t 1 && -t 2 ]] && command -v "tput" >& /dev/null ; then
+        function TPUT()
+        {
+            tput "$@"
+        }
+    else
+        function TPUT() { : ; }
+    fi
+
+    #now call thy self
+    TPUT "$@"
+}
+
+function ERROR()
+{
+    TPUT setaf 1 >&2
+    while read; do
+        echo "ERROR: $REPLY"
+    done <<< "$@" >&2
+    TPUT sgr0 >&2
+}
+
+function WARN()
+{
+    TPUT setaf 3
+    while read; do
+        echo "WARN: $REPLY"
+    done <<< "$@"
+    TPUT sgr0
+}
+
+function INFO()
+{
+    TPUT setaf 2
+    while read; do
+        echo "INFO: $REPLY"
+    done <<< "$@"
+    TPUT sgr0
+}
+
 MYDIR="$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )"
 
 # Batch Script that starts SCREEN
@@ -20,7 +61,7 @@ BS="${MYDIR}/_interactive"
 # Interactive screen script
 IS="${MYDIR}/_interactive_screen"
 
-echo "=*~-  Please enter your resource requirements.  -~*="
+INFO "=*~-  Please enter your resource requirements.  -~*="
 echo " "
 read -e -p "How many CPU cores? :: " -i "2" REQCPU
 read -e -p "How much memory (in MB)? :: " -i "8192" REQMEM
@@ -29,26 +70,33 @@ read -e -p "What QOS? :: " -i "free" QOS
 read -e -p "What partition? :: " -i "work" PARTITION
 
 echo " "
-echo "Spawning job with the following resources:"
-echo "     Processors: ${REQCPU}"
-echo "         Memory: ${REQMEM}"
-echo "  Runtime limit: ${REQTIME}"
-echo "            QOS: ${QOS}"
-echo "      Partition: ${PARTITION}"
+
+INFO "Spawning job with the following resources:"
+INFO "     Processors: ${REQCPU}"
+INFO "         Memory: ${REQMEM}"
+INFO "  Runtime limit: ${REQTIME}"
+INFO "            QOS: ${QOS}"
+INFO "      Partition: ${PARTITION}"
+
 echo " "
 
 # Submit the job and get the job id
-JOB="$( sbatch --cpus-per-task="${REQCPU}" --mem="${REQMEM}" \
+if ! JOB="$( sbatch --cpus-per-task="${REQCPU}" --mem="${REQMEM}" \
     --time="${REQTIME}" --qos="${QOS}" --partition="${PARTITION}"\
     --output=/dev/null --error=/dev/null "$@" "${BS}" \
-    |& egrep -o -e "\b[0-9]+$" )"
+    |& egrep -o -e "\b[0-9]+$" )"; then
+
+    ERROR "Failed to create job. Please double-check all settings are valid."
+    exit 1
+fi
+
 
 # Make sure the job is always canceled
 # Relying on $PATH for scancel
-trap "{ echo 'Exit triggered. Cancelling job.'; \
-    scancel -q "${JOB}"; exit; }" SIGINT SIGTERM EXIT
+trap "{ echo 'Exit triggered. Cancelling job.' >&2 ; \
+    scancel -q "${JOB}"; exit ; }" EXIT
 
-echo "Waiting for JOBID ${JOB} to start"
+INFO "Waiting for JOBID ${JOB} to start"
 while : ; do
     sleep 1s
 
@@ -59,8 +107,7 @@ while : ; do
         # Job is running, break the while loop
         break
     elif [[ "${STATUS}" != "PD" ]]; then
-        echo "Job is not Running or Pending. Aborting"
-        scancel "${JOB}"
+        # we can just let the trap cancel our job for us
         exit 1
     fi
 
@@ -74,7 +121,10 @@ NODE="$( srun --jobid="${JOB}" -N1 hostname )"
 
 sleep 1s
 
+# sacrific security for user experience
 ssh -X -o StrictHostKeyChecking=no -c arcfour -C \
     -t "${NODE}" "${IS}" "slurm${JOB}"
+
+INFO "Wrapping up..."
 
 # The trap will now cancel the job before exiting.
